import type { AppData } from './types'

export const DEMO_DATA: AppData = {
  organizations: [
    {
      id: 'org_aurora',
      name: 'Indus Health Collective',
      slug: 'indus-health',
      regionalSettings: {
        countryCode: 'PK',
        locale: 'en-PK',
        currency: 'PKR',
        defaultTimeZone: 'Asia/Karachi',
        callingCode: '+92',
      },
      governanceSettings: {
        policyProfileIds: ['privacy-baseline'],
        dataResidencyRegion: 'organization-defined',
        recordRetentionDays: 2555,
        requireMfa: true,
        auditTrailRequired: true,
        consentTrackingRequired: true,
      },
    },
    {
      id: 'org_harbor',
      name: 'Sehat Family Clinics',
      slug: 'sehat-family',
      regionalSettings: {
        countryCode: 'PK',
        locale: 'ur-PK',
        currency: 'PKR',
        defaultTimeZone: 'Asia/Karachi',
        callingCode: '+92',
      },
      governanceSettings: {
        policyProfileIds: ['privacy-baseline'],
        dataResidencyRegion: 'organization-defined',
        recordRetentionDays: 2555,
        requireMfa: true,
        auditTrailRequired: true,
        consentTrackingRequired: true,
      },
    },
  ],
  clinics: [
    {
      id: 'clinic_aurora_main',
      organizationId: 'org_aurora',
      name: 'Indus Clifton Clinic',
      city: 'Karachi',
      timezone: 'Asia/Karachi',
    },
    {
      id: 'clinic_aurora_east',
      organizationId: 'org_aurora',
      name: 'Indus Gulberg Clinic',
      city: 'Lahore',
      timezone: 'Asia/Karachi',
    },
    {
      id: 'clinic_harbor_downtown',
      organizationId: 'org_harbor',
      name: 'Sehat Blue Area Clinic',
      city: 'Islamabad',
      timezone: 'Asia/Karachi',
    },
  ],
  practitioners: [
    {
      id: 'prac_a1',
      organizationId: 'org_aurora',
      clinicId: 'clinic_aurora_main',
      fullName: 'Dr. Syed Imran Garderzi',
      email: 'imran.garderzi@indus.demo',
      phone: '+92 300 555 0101',
      specialties: ['general_medicine'],
      active: true,
      professionalSummary:
        'Family physician providing primary care, preventive checkups, and long-term health guidance for adults and families.',
      qualifications: ['MBBS', 'Family Medicine'],
      languages: ['English', 'Urdu'],
      availabilitySummary: 'Monday–Thursday · 9:00 AM–2:00 PM',
      acceptingPatients: true,
    },
    {
      id: 'prac_a2',
      organizationId: 'org_aurora',
      clinicId: 'clinic_aurora_main',
      fullName: 'Dr. Arifa Imran',
      email: 'arifa.imran@indus.demo',
      phone: '+92 301 555 0102',
      specialties: ['gynecology'],
      active: true,
      professionalSummary:
        'Gynecologist focused on women’s health, preventive screening, and maternal care.',
      qualifications: ['MBBS', 'FCPS Obstetrics & Gynecology'],
      languages: ['English', 'Urdu'],
      availabilitySummary: 'Tuesday–Saturday · 11:00 AM–5:00 PM',
      acceptingPatients: true,
    },
    {
      id: 'prac_a3',
      organizationId: 'org_aurora',
      clinicId: 'clinic_aurora_main',
      fullName: 'Dr. Syeda Sheherbano',
      email: 'sheherbano@indus.demo',
      phone: '+92 302 555 0103',
      specialties: ['dentistry'],
      active: true,
      professionalSummary:
        'Dentist focused on preventive care, restorative treatment, and comfortable patient experiences.',
      qualifications: ['BDS', 'General Dentistry'],
      languages: ['English', 'Urdu'],
      availabilitySummary: 'Monday–Saturday · 10:00 AM–6:00 PM',
      acceptingPatients: true,
    },
    {
      id: 'prac_a4',
      organizationId: 'org_aurora',
      clinicId: 'clinic_aurora_east',
      fullName: 'Dr. Syeda Zainab',
      email: 'zainab@indus.demo',
      phone: '+92 303 555 0144',
      specialties: ['cardiology'],
      active: true,
      professionalSummary:
        'Cardiology consultant focused on cardiac risk review, monitoring plans, and patient education.',
      qualifications: ['MBBS', 'FCPS Cardiology'],
      languages: ['English', 'Urdu'],
      availabilitySummary: 'Monday, Wednesday, Friday · 3:00–7:00 PM',
      acceptingPatients: true,
    },
    {
      id: 'prac_h1',
      organizationId: 'org_harbor',
      clinicId: 'clinic_harbor_downtown',
      fullName: 'Dr. Syed Imran Garderzi',
      email: 'imran.garderzi@sehat.demo',
      phone: '+92 304 555 0201',
      specialties: ['general_medicine'],
      active: true,
      professionalSummary:
        'Family physician supporting preventive care and everyday primary consultations.',
      qualifications: ['MBBS', 'Family Medicine'],
      languages: ['English', 'Urdu'],
      availabilitySummary: 'Monday–Friday · 9:00 AM–1:00 PM',
      acceptingPatients: true,
    },
    {
      id: 'prac_h2',
      organizationId: 'org_harbor',
      clinicId: 'clinic_harbor_downtown',
      fullName: 'Dr. Arifa Imran',
      email: 'arifa.imran@sehat.demo',
      phone: '+92 305 555 0202',
      specialties: ['gynecology'],
      active: true,
      professionalSummary:
        'Gynecologist providing women’s health consultations and follow-up care.',
      qualifications: ['MBBS', 'FCPS Obstetrics & Gynecology'],
      languages: ['English', 'Urdu'],
      availabilitySummary: 'Tuesday–Sunday · 12:00–6:00 PM',
      acceptingPatients: true,
    },
  ],
  patients: [
    {
      id: 'pat_a1',
      organizationId: 'org_aurora',
      clinicId: 'clinic_aurora_main',
      fullName: 'Jordan Ellis',
      dateOfBirth: '1991-04-12',
      phone: '+92 310 555 1001',
      assignedPractitionerId: 'prac_a1',
      notes: 'Annual physical due in September.',
    },
    {
      id: 'pat_a2',
      organizationId: 'org_aurora',
      clinicId: 'clinic_aurora_main',
      fullName: 'Aisha Rahman',
      dateOfBirth: '1986-11-03',
      phone: '+92 311 555 1002',
      assignedPractitionerId: 'prac_a2',
    },
    {
      id: 'pat_a3',
      organizationId: 'org_aurora',
      clinicId: 'clinic_aurora_main',
      fullName: 'Noah Patel',
      dateOfBirth: '2015-07-21',
      phone: '+92 312 555 1003',
      assignedPractitionerId: 'prac_a3',
      notes: 'Blood-pressure follow-up with cardiology.',
    },
    {
      id: 'pat_a4',
      organizationId: 'org_aurora',
      clinicId: 'clinic_aurora_east',
      fullName: 'Grace Kim',
      dateOfBirth: '1978-02-18',
      phone: '+92 313 555 1044',
      assignedPractitionerId: 'prac_a4',
    },
    {
      id: 'pat_h1',
      organizationId: 'org_harbor',
      clinicId: 'clinic_harbor_downtown',
      fullName: 'Marcus Webb',
      dateOfBirth: '1994-09-09',
      phone: '+92 320 555 2001',
      assignedPractitionerId: 'prac_h1',
    },
    {
      id: 'pat_h2',
      organizationId: 'org_harbor',
      clinicId: 'clinic_harbor_downtown',
      fullName: 'Sofia Alvarez',
      dateOfBirth: '1990-01-30',
      phone: '+92 321 555 2002',
      assignedPractitionerId: 'prac_h2',
    },
  ],
  memberships: [
    {
      id: 'mem_aurora_admin',
      organizationId: 'org_aurora',
      displayName: 'Clinic Admin',
      email: 'admin@indus.demo',
      role: 'admin',
      clinicIds: ['clinic_aurora_main', 'clinic_aurora_east'],
    },
    {
      id: 'mem_harbor_admin',
      organizationId: 'org_harbor',
      displayName: 'Clinic Admin',
      email: 'admin@sehat.demo',
      role: 'admin',
      clinicIds: ['clinic_harbor_downtown'],
    },
  ],
  context: {
    organizationId: 'org_aurora',
    clinicId: 'clinic_aurora_main',
    membershipId: 'mem_aurora_admin',
  },
}
